name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_x86_64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: LDFLAGS=-static ./configure
    - name: make
      run: make -j$(nproc) && mv bash bash-x86_64-linux
    - name: upload artifact
      uses: actions/upload-artifact@v4.6.1
      with:
         path: bash-x86_64-linux
    - name: Upload bash to GitHub Releases
      uses: softprops/action-gh-release@v1
      with: 
        files: "bash"  # This grabs the output
        tag_name: latest
        token: ${{ secrets.GITHUB_TOKEN }}
  build_x86_32:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: LDFLAGS="-static" CCFLAGS="-m32" ./configure
    - name: make
      run: make -j$(nproc) && mv bash bash-x86_32-linux
    - name: upload artifact
      uses: actions/upload-artifact@v4.6.1
      with:
         path: bash-x86_32-linux
    - name: Upload bash to GitHub Releases
